local AddOnFolderName, private = ...
local L = _G.LibStub("AceLocale-3.0"):NewLocale(AddOnFolderName, "enUS", true)

L["Alerts"] = true
L["Completed Achievement Criteria"] = true
L["Completed Quest Objectives"] = true
L["Drag to set the spawn point for targeting buttons."] = true
L["Detection"] = true
L["Duration"] = true
L["Hide Anchor"] = true
L["Horizontal offset from the anchor point."] = true
L["Ignore Mute"] = true
L["Interval"] = true
L["NPCs"] = true
L["Play alert sounds when sound is muted."] = true
L["Reset Position"] = true
L["Screen Flash"] = true
L["Screen Location"] = true
L["Show Anchor"] = true
L["Spawn Point"] = true
L["The number of minutes before an NPC will be detected again."] = true
L["The number of minutes a targeting button will exist before fading out."] = true
L["Vertical offset from the anchor point."] = true
L["X Offset"] = true
L["Y Offset"] = true

L["BOTTOM"] = "Bottom"
L["BOTTOMLEFT"] = "Bottom Left"
L["BOTTOMRIGHT"] = "Bottom Right"
L["CENTER"] = "Center"
L["LEFT"] = "Left"
L["RIGHT"] = "Right"
L["TOP"] = "Top"
L["TOPLEFT"] = "Top Left"
L["TOPRIGHT"] = "Top Right"

-- ----------------------------------------------------------------------------
-- Vignettes
-- ----------------------------------------------------------------------------
local VL = _G.LibStub("AceLocale-3.0"):NewLocale(AddOnFolderName .. "Vignette", "enUS", true)

VL["Aarkos - Looted Treasure"] = true
VL["Abandoned Fishing Pole"] = true
VL["Alpha Bat"] = true
VL["Amateur Hunters"] = true
VL["Anchorite's Sojourn"] = true
VL["Avatar of Sothrecar"] = true
VL["Beastmaster Pao'lek"] = true
VL["BH Master Scout"] = true
VL["Blood Moon Boss"] = true
VL["Burning Front"] = true
VL["Cache of Infernals"] = true
VL["Cave Keeper"] = true
VL["Cindral"] = true
VL["Coldstomp"] = true
VL["Coura, Master of Arcana"] = true
VL["Dead Orc Captain"] = true
VL["Dorg"] = true
VL["Embaari Defense Crystal"] = true
VL["Enavra Varandi"] = true
VL["Fel Saberon Shaman"] = true
VL["Foreling Worship Circle"] = true
VL["Forsaken Deathsquad"] = true
VL["Frenzied Animus"] = true
VL["Giant Python"] = true
VL["Giant Raptor"] = true
VL["Giantstalker Hunting Party"] = true
VL["Giblette the Cowardly"] = true
VL["Gorger the Hungry"] = true
VL["Haakun, The All-Consuming"] = true
VL["Helmouth Raiders"] = true
VL["Hook & Sinker"] = true
VL["Horn of the Siren"] = true
VL["Houndmaster Jax'zor"] = true
VL["IH Elite Sniper"] = true
VL["Invasion Point: Devastation"] = true
VL["Iron Front Captain 1"] = true
VL["Iron Front Captain 2"] = true
VL["Iron Front Captain 3"] = true
VL["Iron Houndmaster"] = true
VL["Iron Tunnel Foreman"] = true
VL["Kenos the Unraveller"] = true
VL["Krahl Deathwind"] = true
VL["Lava-Gorged Goren"] = true
VL["Light the Braziers"] = true
VL["Lost Ettin"] = true
VL["Mandrakor the Night Hunter"] = true
VL["Murktide Alpha"] = true
VL["Night Haunter"] = true
VL["Oasis Icemother"] = true
VL["Ogre Primalist"] = true
VL["Pale Assassin"] = true
VL["Pale Gone Fishin'"] = true
VL["Pale Spider Broodmother"] = true
VL["Panther Saberon Boss"] = true
VL["Perrexx the Corruptor"] = true
VL["Pit-Slayer"] = true
VL["Protectors of the Grove"] = true
VL["Purging the River"] = true
VL["Ravager Broodlord"] = true
VL["Rogond"] = true
VL["Saberon Blademaster"] = true
VL["Saberon Shaman"] = true
VL["Sea Giant King"] = true
VL["Sea Hydra"] = true
VL["Sea Lord Torglork"] = true
VL["Seek & Destroy Squad"] = true
VL["Shadowflame Terror"] = true
VL["Shadowmoon Cultist Ritual"] = true
VL["Shaman Fire Stone"] = true
VL["Shivering Ashmaw Cub"] = true
VL["Skog"] = true
VL["Slogtusk the Corpse Eater"] = true
VL["Stoneshard Broodmother"] = true
VL["Stormdrake Matriarch"] = true
VL["Syphonus & Leodrath"] = true
VL["Szirek"] = true
VL["Thane's Mead Hall"] = true
VL["The Beastly Boxer"] = true
VL["The Voidseer"] = true
VL["Trecherous Stallions"] = true
VL["Undgrell Attack"] = true
VL["Venomshade (Plant Hydra)"] = true
VL["Wakkawam"] = true
VL["Wandering Vindicator - Looted Treasure"] = true
VL["Worg Pack"] = true
VL["Worgen Stalkers"] = true
VL["Xothear, The Destroyer"] = true
VL["Yggdrel the Corrupted"] = true
VL["Zoug"] = true
VL["Zulk"] = true
